### ISSUE TITLE
Not working on Vivaldi

### ISSUE THREAD

**Issue by ZimbiX** [ZimbiX/youtube-fast-fullscreen-toggle#2]
It would appear that Vivaldi needs a longer delay before revealing the fluff again when entering fullscreen. It looks like it might be doing an extra repaint, with the toolbars introducing another step in the transition. I'll have to make the code smarter to somehow poll until it's finished transitioning. Users, in the meantime, you could use the script with Tampermonkey and try adjusting the delays in the code yourself - on my new Linux laptop, it looks like the `setTimeout(showFluff, DELAY)` needs to have the delay be at least 150 (ms). Too high a delay though, and leaving fullscreen will take longer unnecessarily. Hence I'll need to again separate the codepaths for entering and exiting fullscreen to use different delays.

**Comment by Fred-Vatin** [comment]
![medal](https://media.tenor.co/images/50742bfb14a3e7d240dd80f12978a2a3/tenor.gif)

Pretty simple but efficient. What Youtube devs were supposed to to. It works on Vivaldi here. A little slower with extra steps during exiting fullscreen but I fear there’s nothing can be done to improve further. This is already a game changer as it is. Google needs to wake up.

**Comment by ZimbiX** [comment]
This might be resolved now; testing necessary

**Comment by ZimbiX** [comment]
Mmm, even with the fluff permanently hidden, the intermediate step in the Vivaldi fullscreen transition is very noticeable. I don't know that I can actually do anything about that =\

**Comment by ZimbiX** [comment]
It seems to be working as well as I can make it now, and it's a huge improvement over the vanilla experience. So marking this issue resolved.
