### ISSUE TITLE
Tampermonkey script won't trigger unless page is reloaded (in Vivaldi)

### ISSUE THREAD

**Issue by Pathduck** [ZimbiX/youtube-fast-fullscreen-toggle#7]
Hi, I've been using this as a Tampermonkey script for a while now, but an issue is that it won't trigger unless the YT page is reloaded. I've tried changing some of the Settings parameters like "Run at" but it doesn't help.

If I watch the Tampermonkey icon I can see the overlay "1" only appears after a page load.

Other than that it seem to work really well but it would be nice if this could be figured out.

This is using Vivaldi 3.8.

**Comment by ZimbiX** [comment]
Interesting. Thanks for the info; I'll look into it when I have time

**Comment by ZimbiX** [comment]
It seems that YouTube doesn't do a regular page load when you navigate around the site; instead doing something similar to [turbolinks](https://github.com/turbolinks/turbolinks), where it swaps out the page content. Thus the extension (and when run in Tampermonkey) does not re-run after navigating to another page. For example, starting from the watchlist page, then clicking on the first video. It does appear to still work when navigating from one video to another; I guess in that case, the DOM elements which had listeners attached when the extension first ran are reused.

I'm looking into something like's jQuery delegate - to dynamically handle an event based on a particular CSS selector, allowing it to apply to new DOM elements too.

**Comment by ZimbiX** [comment]
Or alternatively, I could use `window.onurlchange` to listen for URL changes.

**Comment by ZimbiX** [comment]
Fixed in 2.5.0. The new version has been submitted to the Chrome Web Store for review; in the meantime, the latest version can be used in Tampermonkey.

**Comment by Pathduck** [comment]
Awesome, thanks for the fix, I just tested and now it triggers on every video 👍 
I didn't think of just changing the match to `youtube.com/*` but apparently there was other code changes needed too.

By the way would it be possible to add a header to make it auto-update when using a user-script directly from Git or would you have to upload to Greasyfork or similar? I mean the `downloadURL` should be enough right? Or maybe you have to add a `updateURL` header too.

**Comment by ZimbiX** [comment]
No problem. I'd noticed something weird was happening sometimes; thanks for the motivation to look into it!

I haven't made use of userscript auto-updating before. I didn't see much useful official documentation, but I followed [this great StackOverlow answer](https://stackoverflow.com/a/38025376/1239774). As far as I can tell, it should work, but I haven't yet observed Tampermonkey performing an update. I notice that Tampermonkey's settings page has two different update interval settings - I'm not sure which would apply here, but the options are not very granular:

![Screenshot from 2021-05-23 12-34-30](https://user-images.githubusercontent.com/2916331/119246285-bc791200-bbc3-11eb-8019-13b969f4da40.png)

I think I'd prefer not to upload it to a site like Greasyfork if I don't have to, as it's another thing I'd have to maintain. I don't know that user discovery would benefit that much from it.

I mostly use it in the extension form myself, to reflect the experience of how I imagine most people will be using it. I'll try switching to Tampermonkey and decreasing the version number to try to see it perform an update.

**Comment by ZimbiX** [comment]
Ooh, it looks like the update setting needs to be enabled per script:

![Screenshot from 2021-06-05 17-10-31](https://user-images.githubusercontent.com/2916331/120883504-f6650200-c620-11eb-88f9-569690641436.png)

**Comment by ZimbiX** [comment]
Ah ha - and then the update column becomes clickable to update on demand! =)

![Screenshot from 2021-06-05 17-13-44 - annotated](https://user-images.githubusercontent.com/2916331/120883641-991d8080-c621-11eb-9aa0-5abcde9382aa.png)

**Comment by Pathduck** [comment]
@ZimbiX Oh wow, I had no idea ... how on earth could I have missed that option??? 😖 

The way to manually trigger an update either by clicking the "last updated" text or by selecting a script and choosing Trigger Update from the dropdown is not exactly super-intuitive. I believe I tried the latter option (dropdown) but unless the script setting is enabled it will fail no matter.

Thanks a lot for finding this! 👍
